[SECRETS]
apiurl = https://data.digitalwaters.org/upload/
apikey = YOUR_API_KEY_HERE
# Device status endpoint. Leave blank to disable status reporting.
statusurl =
accountnumber = YOUR_ACCOUNT_NUMBER_HERE

[GENERAL]
sleepinterval = 300
logmaxfilesizemb = 5
logfilecount = 20

